- id: eight-legged-essay
  title:
    en: "Eight-Legged Essays for Programmers"
    zh: "八股文"
  description:
    en: "Comprehensive technical interview preparation materials covering essential topics for software engineers. Master API design, algorithms, databases, system design, and more."
    zh: "全面的技术面试准备资料，涵盖软件工程师必需的关键主题。掌握 API 设计、算法、数据库、系统设计等内容。"
  thumbnail: "/assets/images/products/eight-legged-essay.jpg"
  release_date: 2025-12-18
  tags: ["interview", "technical", "algorithms", "system-design"]
  featured: true